
econs <- tibble(full.nm = c("Ben Bernanke",
                            "Janet Yellen",
                            "Paul Krugman",
                            "Noah Smith",
                            "Philip Lowe",
                            "Glenn Stevens",
                            "Steve Keen",
                            "Alan Greenspan",
                            "Ludwig von Mises"),
                abr.nm= c("Ben",
                          "Janet",
                          "Paul",
                          "Noah",
                          "Philip",
                          "Glenn",
                          "Keen",
                          "Greenspan",
                          "Mises"),
                pol.mon = c(0.8,
                              0.6,
                             0.45,
                              0.1,
                              0.4,
                              0.6,
                              -0.8,
                              -0.6,
                              -1),
                pol.fis = c(-0.1,
                           -0.3,
                           -0.7,
                           -0.1,
                           0,
                           0,
                           -0.9,
                           0.3,
                           1))

devtools::use_data(econs, internal = F, overwrite = T)
